### PR TITLE
resolve merge conflicts for previous work to retrieve block hash and number for eth tx

### PR DESCRIPTION
**Pull request by alex-sumner**
Time spent on this PR:
2 hours

Closes #NUMBER_OF_ISSUE

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: N/A

# What is the new behavior?

-
-
-

# Does this introduce a breaking change?

- [ ] Yes
- [ ] No

# Other information

### CODE REVIEW

**Comment by Eikix** [comment]
What is this PR's purpose?

**Comment by Eikix** [comment]
Ahh it appears the latest merges to main have overwritten your work on eth txs. Is that it?

**Comment by alex-sumner** [comment]
I am trying to merge the earlier work (putting block number and hash from
Starknet tx receipt into eth tx). It was twice blocked by merge conflicts.
This resolves them.

**Comment by alex-sumner** [comment]
Yes

**Review by Eikix — APPROVED** [review]
thanks for your patience! 💪

**Comment by alex-sumner** [comment]
No problem, all good!

**Pull request merged**
