### PR TITLE
added eth_accounts feat

### PR DESCRIPTION
**Pull request by phklive**
Time spent on this PR: 30 min

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Feat not implemented / todo

Issue Number: #53 

# What is the new behavior?

When requesting client accounts returning empty vector

# Does this introduce a breaking change?

- [ ] Yes
- [X] No

# Other information

### CODE REVIEW

**Review by Eikix — CHANGES_REQUESTED** [review]
could you add method documentation in `docs/methods` (as per other examples) and also add your ✅ in docs/api_status.md

**Comment by phklive** [comment]
Done

**Review by danilowhk — APPROVED** [review]
lgtm!

**Review by Eikix — APPROVED** [review]
lgtm

**Pull request merged**
