### PR TITLE
add : getTxByBlockHashAndIndex

### PR DESCRIPTION
**Pull request by Rphad**
Implement getTxByBlockHashAndIndex

Time spent on this PR: 0.1

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Unimplemented

Issue Number: N/A

# What is the new behavior?

Returns a `Transaction` struct when given a block hash and index

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

Please treat this PR carefully, as I'm new to contributing, Rust, and this codebase. I thus may have made mistakes

### CODE REVIEW

**Review by Eikix — CHANGES_REQUESTED** [review]
Nice PR! Smart trick:D

Can you add a .hurl file and test locally that your feature works? Thanks

**Comment by Rphad** [comment]
I added a hurl example in the `rpc-call-examples` folder and ran `cargo test --all`, which succeeded. Is this what you meant ?

**Comment by Eikix** [comment]
I meant to try and run `cargo run --package  kakarot_rpc` and then in another terminal `hurl rpc-call-examples/transactionByBlockHashAndIndex.hurl` 

you'd have to install hurl

**Comment by Eikix** [comment]
Nice PR! Ready to merge, you'll have to resolve conflicts first:)

**Review by Eikix — APPROVED** [review]
gg!

**Review by Eikix — CHANGES_REQUESTED** [review]
If you can pull latest version of main -> rebase on main -> resolve conflicts, we're good to go:)

**Comment by Rphad** [comment]
Not sure what's happening

**Comment by Rphad** [comment]
Making a new, cleaner PR

**Pull request closed without merging**
